name: CI/CD for Convert to markdown

on:
  push:
    branches:
      - convert-markdown
  pull_request:
    branches:
      - convert-markdown

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Build for ARM64 on Amazon Linux 2023
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 0
      run: go build -tags lambda.norpc -o bootstrap main.go

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        LAMBDA_FUNCTION_NAME: ${{ secrets.CONVERT_MARKDOWN_LAMBDA_FUNCTION_NAME }}
        GPT_SERVER: ${{ secrets.GPT_SERVER }}
        PROMPT_CONTENT_1: ${{ secrets.PROMPT_CONTENT_1 }}
        PROMPT_CONTENT_2: ${{ secrets.PROMPT_CONTENT_2 }}
        PROMPT_CONTENT_3: ${{ secrets.PROMPT_CONTENT_3 }}
      run: |
        zip function.zip bootstrap
        aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --zip-file fileb://function.zip