name: CI/CD for Crawling

on:
  push:
    branches:
      - crawling
  pull_request:
    branches:
      - crawling
defaults:
  run:
    working-directory: ./crawling
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Build for ARM64 on Amazon Linux 2023
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 0
      run: go build -tags lambda.norpc -o bootstrap main.go

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        LAMBDA_FUNCTION_NAME: ${{ secrets.CRAWLING_LAMBDA_FUNCTION_NAME }}
        BASE_URL: ${{ secrets.BASE_URL }}
        BASE_URL_DETAIL: ${{ secrets.BASE_URL_DETAIL }}
      run: |
        zip function.zip bootstrap
        aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --zip-file fileb://function.zip